Task 5
nobleaustine/prapro pull request #4
Opened 2024-02-12 00:14 UTC by nobleaustine

Task 5 completed

2024-02-12 04:08 UTC, FayazRahman approved these changes

2024-02-12 04:08 UTC, FayazRahman commented on task_5/task_5.py
> +# Testing
add test as a pytest in separate file. See https://docs.pytest.org/en/7.1.x/getting-started.html#create-your-first-test

2024-02-12 04:08 UTC, FayazRahman commented on task_5/task_5.py
> +        ext = extension.split('.')[-1]
Check if `os.path.splitext` will be enough here.

2024-02-12 04:10 UTC, FayazRahman requested changes
Small changes needed

2024-02-12 14:20 UTC, nobleaustine commented
used os.path.splitext and added separate test file

2024-02-13 03:56 UTC, FayazRahman requested changes
Rename `test_Downloader.py` to `test_downloader.py`

2024-02-13 04:47 UTC, nobleaustine commented
updated the name to test_downloader.py

2024-02-14 06:50 UTC, FayazRahman approved these changes

2024-02-14 07:19 UTC, nobleaustine commented
all issues resolved

2024-02-14 07:19 UTC, merged